name: Build Kernel Packages 

on:
  workflow_dispatch:
  push:

env:
  PACKAGES_DIR : /home/runner/pkg
  KERNEL_DIR : ${{ github.workspace }}
  GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
             mkdir -p ${{ env.PACKAGES_DIR }}
             docker run --rm -v $PACKAGES_DIR:/buildd -v ${{env.KERNEL_DIR}}:/buildd/sources quay.io/droidian/build-essential:next-amd64 bash -c "cd /buildd/sources && RELENG_HOST_ARCH="arm64" releng-build-package"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: /home/runner/pkg

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: kernel
        path: ./kernel

    - name: Clone APT Repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone https://${{ secrets.PAT }}@github.com/WHO53/apt.git --depth=1
        mkdir -p apt/packages
        cd apt/packages
        rm -f linux*
        cp ../../kernel/*.deb .
        git add .
        git commit -m "Update kernel packages:${GITHUB_SHA::7}"
        git push
      env:
        PAT: ${{ secrets.PAT }}
